apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-failed
  labels:
    app: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: deployment-failed-container
          image: busybox
          command: ["sh", "-c", "exit 1"]  # Causes the pod to immediately fail

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-crashloopbackoff
  labels:
    app: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: deployment-crashloopbackoff-container
          image: busybox
          command: ["sh", "-c", "while true; do echo 'CrashLoop'; sleep 1; done"]  # Simulates crash loop

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-error
  labels:
    app: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: deployment-error-container
          image: busybox
          command: ["sh", "-c", "exit 2"]  # Causes the container to exit with an error code
